version: '3'

services:
    client:
        build:
          context:  .
          dockerfile:  ./client/Dockerfile
        ports:
          - "8080:80"
        restart: always
        networks:
          - app-network
    server:
        build:
          context:  .
          dockerfile:  ./server/Dockerfile
        ports:
            - "3030:3030"
        restart: always
        networks:
          - app-network
networks:
  app-network:
    driver: bridge